-- Nếu category_id là AUTO_INCREMENT, bỏ qua cột này
INSERT INTO categories (name, slug) VALUES
('Consumer Electronics', 'consumer-electronics'),
('Home Appliances', 'home-appliances'),
('Cooling Devices', 'cooling-devices'),
('Audio Equipment', 'audio-equipment'),
('Lighting Devices', 'lighting-devices');

-- Thêm dữ liệu vào bảng subcategories
INSERT INTO subcategories (name, category_id) VALUES
    ('Smartphones', 1),
    ('Televisions', 1),
    ('Laptops', 1),
    ('Refrigerators', 2),
    ('Washing Machines', 2),
    ('Vacuum Cleaners', 2),
    ('Air Conditioners', 3),
    ('Fans', 3),
    ('Speakers', 4),
    ('Headphones', 4),
    ('Wall Lights', 5),
    ('Table Lamps', 5);

-- Thêm dữ liệu vào bảng stores
INSERT INTO stores (name, description, address, phone)
VALUES
    ('ElectroAptech', 'Electronics and gadgets store', '285 Doi CN', '1234567890');

-- Thêm dữ liệu vào bảng brands
INSERT INTO brands (name, description) VALUES
    ('Samsung', 'Offers products such as smartphones, TVs, washing machines, and home appliances.'),
    ('Apple', 'Known for its smartphones, tablets, laptops, and other innovative technology products.'),
    ('Sony', 'Recognized for products such as TVs, cameras, and audio equipment.'),
    ('LG', 'Known for its TVs, washing machines, refrigerators, and other home appliances.'),
    ('Panasonic', 'Provides products such as refrigerators, washing machines, and consumer electronics.'),
    ('Sharp', 'Offers TVs, air conditioners, and other home appliances.'),
    ('Bosch', 'Famous for home appliances such as washing machines, microwaves, and dishwashers.'),
    ('Toshiba', 'Provides products such as refrigerators, washing machines, and other electronics.'),
    ('Aqua', 'A brand under Haier, offering refrigerators, washing machines, and other home appliances.'),
    ('Xiaomi', 'Provides smartphones, smart home devices, and other technology products.'),
    ('Huawei', 'Known for smartphones and other technology devices.'),
    ('Dell', 'Offers laptops, desktops, and accessories.'),
    ('HP', 'Famous for computers, printers, and office equipment.'),
    ('Lenovo', 'Provides laptops, desktops, and other electronic devices.'),
    ('Asus', 'Offers laptops, motherboards, and accessories.'),
    ('MSI', 'Known for gaming laptops and computer components.'),
    ('Sunhouse', 'Known for affordable and practical home appliances.'),
    ('Kangaroo', 'Offers a wide range of home appliances with innovative features.');

INSERT INTO products (name, description, price, price_sale, category_id, subcategory_id, brand_id, quantity, store_id, avatar_product)
VALUES


    ('iPhone 13', 'Latest model with improved battery life and camera.', 699.99, 649.99, 1, 1, (SELECT brand_id FROM brands WHERE name = 'Apple'), 150, 1, 'storage/images/iphone13_1.jpg'),
    ('iPhone 13 Pro Max', 'Max variant with the largest display and top features.', 999.99, 949.99, 1, 1, (SELECT brand_id FROM brands WHERE name = 'Apple'), 60, 1, 'storage/images/iphone-13-pro-max_1.jpg'),
    ('iPhone 14', 'Latest iPhone with improved camera and performance.', 799.99, 749.99, 1, 1, (SELECT brand_id FROM brands WHERE name = 'Apple'), 150, 1, 'storage/images/iphone14_1.jpg'),
    ('iPhone 14 Pro Max', 'Large screen iPhone with top-tier performance and camera capabilities.', 1099.99, 1049.99, 1, 1, (SELECT brand_id FROM brands WHERE name = 'Apple'), 60, 1, 'storage/images/iphone-14-pro-max_1.jpg'),
    ('iPhone 15', 'The latest iPhone model with advanced features.', 1199.99, 1149.99, 1, 1, (SELECT brand_id FROM brands WHERE name = 'Apple'), 100, 1, 'storage/images/iphone15_1.jpg'),
    ('Samsung Galaxy S23', 'Flagship smartphone with high-end specifications.', 799.99, 749.99, 1, 1, (SELECT brand_id FROM brands WHERE name = 'Samsung'), 80, 1, 'storage/images/samsung_galaxy_S23_1.jpg'),
    ('Samsung Galaxy A54', 'Mid-range smartphone with a good balance of performance and features.', 299.99, 249.99, 1, 1, (SELECT brand_id FROM brands WHERE name = 'Samsung'), 100, 1, 'storage/images/samsung_galaxy_A54_1.jpg'),

    ('Samsung QLED TV 65"', 'High-definition QLED TV with vibrant colors and deep blacks.', 1299.99, 1199.99, 1, 2, (SELECT brand_id FROM brands WHERE name = 'Samsung'), 25, 1, 'storage/images/Samsung_QLED-TV_65_1.jpg'),
    ('Samsung Frame TV 50"', 'Stylish TV that doubles as a piece of art.', 999.99, 949.99, 1, 2, (SELECT brand_id FROM brands WHERE name = 'Samsung'), 20, 1, 'storage/images/Samsung_Frame_ TV_ 50_1.jpg'),
    ('LG OLED TV 55"', 'OLED TV with exceptional contrast and color accuracy.', 1499.99, 1399.99, 1, 2, (SELECT brand_id FROM brands WHERE name = 'LG'), 10, 1, 'storage/images/LG_OLED_TV_55_1.jpg'),
    ('LG Nanocell TV 65"', 'NanoCell technology for enhanced color and clarity.', 1399.99, 1299.99, 1, 2, (SELECT brand_id FROM brands WHERE name = 'LG'), 20, 1, 'storage/images/LG_Nanocell_TV_65_1.jpg'),

    ('Asus ZenBook 14', 'Ultrabook with a sleek design and strong performance.', 1199.99, 1099.99, 1, 3, (SELECT brand_id FROM brands WHERE name = 'Asus'), 45, 1, 'storage/images/Asus_Zenbook_14_1.jpg'),
    ('Asus TUF Gaming A15', 'Gaming laptop with durable build and high performance.', 1299.99, 1199.99, 1, 3, (SELECT brand_id FROM brands WHERE name = 'Asus'), 50, 1, 'storage/images/Asus_TUF_Gaming_A15_2.jpg'),
    ('Lenovo ThinkPad X1 Carbon', 'Business laptop known for its durability and performance.', 1499.99, 1399.99, 1, 3, (SELECT brand_id FROM brands WHERE name = 'Lenovo'), 30, 1, 'storage/images/Lenovo_Thinkpad_X1_Carbon_1.jpg'),
    ('Lenovo Yoga 9i', 'Convertible laptop with a high-resolution display and versatile functionality.', 1299.99, 1199.99, 1, 3, (SELECT brand_id FROM brands WHERE name = 'Lenovo'), 40, 1, 'storage/images/Lenovo_Yoga_9i_1.jpg'),

    ('Panasonic NR-BV280QSVN', 'Panasonic NR-BV280QSVN refrigerator with Inverter technology for energy saving.', 899.99, 849.99, 2, 4, (SELECT brand_id FROM brands WHERE name = 'Panasonic'), 50, 1, 'storage/images/Panasonic_NR_1.jpg'),
    ('Panasonic NR-BA228PKV1', 'Panasonic NR-BA228PKV1 refrigerator with modern and convenient design.', 799.99, 749.99, 2, 4, (SELECT brand_id FROM brands WHERE name = 'Panasonic'), 60, 1, 'storage/images/BA228PKV1_4.jpg'),
    ('Toshiba GR-RS682WE-PMV(06)-XK', 'Toshiba GR-RS682WE-PMV(06)-XK refrigerator with optimal cooling technology and energy saving.', 1099.99, 1049.99, 2, 4, (SELECT brand_id FROM brands WHERE name = 'Toshiba'), 30, 1, 'storage/images/RS682WE_1.jpg'),
    ('Toshiba GR-AG66VA(XK)', 'Toshiba GR-AG66VA(XK) refrigerator with luxurious design and large capacity.', 999.99, 949.99, 2, 4, (SELECT brand_id FROM brands WHERE name = 'Toshiba'), 35, 1, 'storage/images/AG66VA(XK)_1.jpg'),

    ('Toshiba AW-B1000GV', 'Toshiba AW-B1000GV offers a spacious drum and multiple wash programs for effective cleaning.', 550.00, 500.00, 2, 5, (SELECT brand_id FROM brands WHERE name = 'Toshiba'), 25, 1, 'storage/images/B1000GV_1.jpg'),
    ('Toshiba TW-BH85S2V', 'Toshiba TW-BH85S2V provides high washing efficiency with smart technology and various settings.', 600.00, 550.00, 2, 5, (SELECT brand_id FROM brands WHERE name = 'Toshiba'), 20, 1, 'storage/images/BH85S2V_1.jpg'),
    ('Samsung WW90J54E0BW/SV', 'Samsung WW90J54E0BW/SV features a large capacity and advanced cleaning technology for thorough washing.', 700.00, 650.00, 2, 5, (SELECT brand_id FROM brands WHERE name = 'Samsung'), 15, 1, 'storage/images/WW90J54E0BWSV_1.jpg'),
    ('Samsung WA10J5710SG/SV', 'Samsung WA10J5710SG/SV is known for its robust build and powerful washing performance.', 650.00, 600.00, 2, 5, (SELECT brand_id FROM brands WHERE name = 'Samsung'), 18, 1, 'storage/images/WA10J5710SGSV_4.jpg'),

    ('Panasonic MC-CL563', 'Compact design, easy to use vacuum cleaner.', 179.99, 169.99, 2, 6, (SELECT brand_id FROM brands WHERE name = 'Panasonic'), 60, 1, 'storage/images/CL563_1.jpg'),
    ('Panasonic MC-CL305', 'Vacuum cleaner with effective dust filtering feature.', 159.99, 149.99, 2, 6, (SELECT brand_id FROM brands WHERE name = 'Panasonic'), 55, 1, 'storage/images/CL305_1.jpg'),
    ('Toshiba VC-PG514', 'Vacuum cleaner with advanced dust filtering technology.', 219.99, 209.99, 2, 6, (SELECT brand_id FROM brands WHERE name = 'Toshiba'), 40, 1, 'storage/images/Toshiba_VC_PG514_1.jpg'),
    ('Toshiba VC-WF500', 'Equipped with HEPA filter and adjustable suction power.', 229.99, 219.99, 2, 6, (SELECT brand_id FROM brands WHERE name = 'Toshiba'), 45, 1, 'storage/images/Toshiba_1.jpg'),  

    ('Toshiba RAS-13N3KV', 'Large capacity air conditioner for quick cooling.', 589.99, 569.99, 3, 7, (SELECT brand_id FROM brands WHERE name = 'Toshiba'), 20, 1, 'storage/images/13N3KV_1.jpg'),
    ('Toshiba RAS-09BKCV', 'Air conditioner with sleek design and high performance.', 439.99, 419.99, 3, 7, (SELECT brand_id FROM brands WHERE name = 'Toshiba'), 45, 1, 'storage/images/09BKCV_1.jpg'),
    ('LG LS-H09VNA', 'Air conditioner with Dual Inverter technology for quiet operation.', 469.99, 449.99, 3, 7, (SELECT brand_id FROM brands WHERE name = 'LG'), 35, 1, 'storage/images/H09VNA_1.jpg'),
    ('LG LS-H12VNA', 'Large capacity air conditioner for efficient cooling in larger rooms.', 569.99, 549.99, 3, 7, (SELECT brand_id FROM brands WHERE name = 'LG'), 30, 1, 'storage/images/H12VNA_1.jpg'),

    ('Samsung AX50R9080S', 'Air cooler with advanced cooling technology and modern design.', 149.99, 139.99, 3, 8, (SELECT brand_id FROM brands WHERE name = 'Samsung'), 15, 1, 'storage/images/may-loc-khong-khi-samsung-ax90r7080-1.jpg'),
    ('Samsung VF-R21', 'Stand fan with wide cooling range and adjustable speed.', 79.99, 74.99, 3, 8, (SELECT brand_id FROM brands WHERE name = 'Samsung'), 30, 1, 'storage/images/Samsung_VF_R21_1.jpg'),
    ('LG WF-181', 'Stand fan with powerful motor and adjustable airflow.', 74.99, 69.99, 3, 8, (SELECT brand_id FROM brands WHERE name = 'LG'), 45, 1, 'storage/images/LG_air_1.jpg'),
    ('LG WF-232', 'Wall fan with high power and efficient cooling.', 94.99, 89.99, 3, 8, (SELECT brand_id FROM brands WHERE name = 'LG'), 20, 1, 'storage/images/LG_WF_232_1.jpg'),

    ('LG XBOOM SK10Y', 'Soundbar with Dolby Atmos technology and high-quality audio.', 699.99, 669.99, 4, 9, (SELECT brand_id FROM brands WHERE name = 'LG'), 20, 1, 'storage/images/SK10Y_1.jpg'),
    ('LG XBOOM RL4', 'Bluetooth speaker with large power and dynamic sound.', 129.99, 119.99, 4, 9, (SELECT brand_id FROM brands WHERE name = 'LG'), 40, 1, 'storage/images/RL4_1.jpg'),
    ('Samsung HW-Q950A', 'Soundbar with Dolby Atmos technology and 11.1.4 channel surround sound.', 1399.99, 1349.99, 4, 9, (SELECT brand_id FROM brands WHERE name = 'Samsung'), 10, 1, 'storage/images/Q950A_1.jpg'),
    ('Samsung Sound Tower MX-T70', 'Bluetooth speaker with high power and LED light effects.', 299.99, 279.99, 4, 9, (SELECT brand_id FROM brands WHERE name = 'Samsung'), 30, 1, 'storage/images/MX-T70_1.jpg'),

    ('Apple AirPods Pro', 'Wireless in-ear headphones with noise cancellation and Siri integration.', 249.99, 229.99, 4, 10, (SELECT brand_id FROM brands WHERE name = 'Apple'), 30, 1, 'storage/images/airportpro_1.jpg'),
    ('Apple AirPods Max', 'Over-ear headphones with high-quality sound and active noise cancellation.', 549.99, 529.99, 4, 10, (SELECT brand_id FROM brands WHERE name = 'Apple'), 10, 1, 'storage/images/airportpromax_1.jpg'),
    ('Sony WF-1000XM4', 'Wireless in-ear headphones with active noise cancellation and excellent sound quality.', 279.99, 259.99, 4, 10, (SELECT brand_id FROM brands WHERE name = 'Sony'), 30, 1, 'storage/images/1000XM5_1.jpg'),
    ('Sony WH-H910N', 'Over-ear headphones with noise cancellation and clear sound.', 199.99, 179.99, 4, 10, (SELECT brand_id FROM brands WHERE name = 'Sony'), 25, 1, 'storage/images/H910N_1.jpg'),


    ('Sunhouse Modern LED Wall Light', 'Modern LED wall light with elegant design and effective illumination.', 79.99, 69.99, 5, 11, (SELECT brand_id FROM brands WHERE name = 'Sunhouse'), 25, 1, 'storage/images/Sunhouse_Modern_LED_Wall_Light_1.jpg'),
    ('Sunhouse Classic Wall Light', 'Classic LED wall light with warm illumination and energy efficiency.', 89.99, 79.99, 5, 11, (SELECT brand_id FROM brands WHERE name = 'Sunhouse'), 20, 1, 'storage/images/Sunhouse_classic_wall_light_1.jpg'),
    ('Kangaroo Elegant Wall Light', 'Kangaroo wall light with a sophisticated design and soft illumination.', 89.99, 79.99, 5, 11, (SELECT brand_id FROM brands WHERE name = 'Kangaroo'), 15, 1, 'storage/images/Kangaroo_Elegant_Wall_Light_1.jpg'),
    ('Kangaroo LED Wall Lamp', 'Kangaroo LED wall lamp with powerful illumination and high performance.', 99.99, 89.99, 5, 11, (SELECT brand_id FROM brands WHERE name = 'Kangaroo'), 18, 1, 'storage/images/Kangaroo_Led_Wall_Lamp_1.jpg'),

    ('Kangaroo Table Lamp', 'Elegant table lamp with energy-saving LED light and stylish finish.', 59.99, 54.99, 5, 12, (SELECT brand_id FROM brands WHERE name = 'Kangaroo'), 15, 1, 'storage/images/Kangaroo_Table_Lamp_1.jpg'),
    ('Xiaomi Table Lamp', 'Smart table lamp with adjustable color temperature and remote control.', 79.99, 74.99, 5, 12, (SELECT brand_id FROM brands WHERE name = 'Xiaomi'), 18, 1, 'storage/images/xiaomi_lamp_1.jpg'),
    ('Panasonic Table Lamp', 'High-quality table lamp with classic design and long-lasting LED.', 89.99, 84.99, 5, 12, (SELECT brand_id FROM brands WHERE name = 'Panasonic'), 10, 1, 'storage/images/Panasonic_Table_Lamp_1.jpg');


INSERT product_images (product_id,image_url) VALUES

(1,'storage/images/iphone13_2.jpg'),
(2,'storage/images/iphone-13-pro-max_2.jpg'),
(3,'storage/images/iphone14_2.jpg'),
(4,'storage/images/iphone-14-pro-max_2.jpg'),
(5,'storage/images/iphone15_2.jpg'),
(6,'storage/images/samsung_galaxy_S23_2.jpg'),
(7,'storage/images/samsung_galaxy_A54_2.jpg'),
(8,'storage/images/Samsung_QLED-TV_65_2.jpg'),
(9,'storage/images/Samsung_Frame_ TV_ 50_2.jpg'),
(10,'storage/images/LG_OLED_TV_55_2.jpg'),
(11,'storage/images/LG_Nanocell_TV_65_2.jpg'),
(12,'storage/images/Asus_Zenbook_14_2.jpg'),
(13,'storage/images/Asus_TUF_Gaming_A15_2.jpg'),
(14,'storage/images/Lenovo_Thinkpad_X1_Carbon_2.jpg'),
(15,'storage/images/Lenovo_Yoga_9i_2.jpg'),
(16,'storage/images/Panasonic_NR_2.jpg'),
(17,'storage/images/BA228PKV1_2.jpg'),
(18,'storage/images/RS682WE_2.jpg'),
(19,'storage/images/AG66VA(XK)_2.jpg'),
(20,'storage/images/B1000GV_2.jpg'),
(21,'storage/images/BH85S2V_2.jpg'),
(22,'storage/images/WW90J54E0BWSV_2.jpg'),
(23,'storage/images/WA10J5710SGSV_2.jpg'),
(24,'storage/images/CL563_2.jpg'),
(25,'storage/images/CL305_2.jpg'),
(26,'storage/images/Toshiba_VC_PG514_2.jpg'),
(27,'storage/images/Toshiba_2.jpg'),
(28,'storage/images/13N3KV_2.jpg'),
(29,'storage/images/09BKCV_2.jpg'),
(30,'storage/images/H09VNA_2.jpg'),
(31,'storage/images/H12VNA_2.jpg'),
(32,'storage/images/may-loc-khong-khi-samsung-ax90r7080-1.jpg'),
(33,'storage/images/Samsung_VF_R21_2.jpg'),
(34,'storage/images/LG_air_2.jpg'),
(35,'storage/images/LG_WF_232_2.jpg'),
(36,'storage/images/SK10Y_2.jpg'),
(37,'storage/images/RL4_2.jpg'),
(38,'storage/images/Q950A_2.jpg'),
(39,'storage/images/MX-T70_2.jpg'),
(40,'storage/images/airportpro_2.jpg'),
(41,'storage/images/airportpromax_2.jpg'),
(42,'storage/images/1000XM5_2.jpg'),
(43,'storage/images/H910N_2.jpg'),
(44,'storage/images/Sunhouse_Modern_LED_Wall_Light_2.jpg'),
(45,'storage/images/Sunhouse_classic_wall_light_2.jpg'),
(46,'storage/images/Kangaroo_Elegant_Wall_Light_2.jpg'),
(47,'storage/images/Kangaroo_Led_Wall_Lamp_2.jpg'),
(48,'storage/images/Kangaroo_Table_Lamp_2.jpg'),
(49,'storage/images/xiaomi_lamp_2.jpg'),
(50,'storage/images/Panasonic_Table_Lamp_2.jpg'),
(1,'storage/images/iphone13_3.jpg'),
(2,'storage/images/iphone-13-pro-max_3.jpg'),
(3,'storage/images/iphone14_3.jpg'),
(4,'storage/images/iphone-14-pro-max_3.jpg'),
(5,'storage/images/iphone15_3.jpg'),
(6,'storage/images/samsung_galaxy_S23_3.jpg'),
(7,'storage/images/samsung_galaxy_A54_3.jpg'),
(8,'storage/images/Samsung_QLED-TV_65_3.jpg'),
(9,'storage/images/Samsung_Frame_ TV_ 50_3.jpg'),
(10,'storage/images/LG_OLED_TV_55_3.jpg'),
(11,'storage/images/LG_Nanocell_TV_65_3.jpg'),
(12,'storage/images/Asus_Zenbook_14_3.jpg'),
(13,'storage/images/Asus_TUF_Gaming_A15_3.jpg'),
(14,'storage/images/Lenovo_Thinkpad_X1_Carbon_3.jpg'),
(15,'storage/images/Lenovo_Yoga_9i_3.jpg'),
(16,'storage/images/Panasonic_NR_3.jpg'),
(17,'storage/images/BA228PKV1_3.jpg'),
(18,'storage/images/RS682WE_3.jpg'),
(19,'storage/images/AG66VA(XK)_3.jpg'),
(20,'storage/images/B1000GV_3.jpg'),
(21,'storage/images/BH85S2V_3.jpg'),
(22,'storage/images/WW90J54E0BWSV_3.jpg'),
(23,'storage/images/WA10J5710SGSV_3.jpg'),
(24,'storage/images/CL563_3.jpg'),
(25,'storage/images/CL305_3.jpg'),
(26,'storage/images/Toshiba_VC_PG514_3.jpg'),
(27,'storage/images/Toshiba_3.jpg'),
(28,'storage/images/13N3KV_3.jpg'),
(29,'storage/images/09BKCV_3.jpg'),
(30,'storage/images/H09VNA_3.jpg'),
(31,'storage/images/H12VNA_3.jpg'),
(32,'storage/images/may-loc-khong-khi-samsung-ax90r7080-1.jpg'),
(33,'storage/images/Samsung_VF_R21_3.jpg'),
(34,'storage/images/LG_air_3.jpg'),
(35,'storage/images/LG_WF_232_3.jpg'),
(36,'storage/images/SK10Y_3.jpg'),
(37,'storage/images/RL4_3.jpg'),
(38,'storage/images/Q950A_3.jpg'),
(39,'storage/images/MX-T70_3.jpg'),
(40,'storage/images/airportpro_3.jpg'),
(41,'storage/images/airportpromax_3.jpg'),
(42,'storage/images/1000XM5_3.jpg'),
(43,'storage/images/H910N_3.jpg'),
(44,'storage/images/Sunhouse_Modern_LED_Wall_Light_3.jpg'),
(45,'storage/images/Sunhouse_classic_wall_light_3.jpg'),
(46,'storage/images/Kangaroo_Elegant_Wall_Light_3.jpg'),
(47,'storage/images/Kangaroo_Led_Wall_Lamp_3.jpg'),
(48,'storage/images/Kangaroo_Table_Lamp_3.jpg'),
(49,'storage/images/xiaomi_lamp_3.jpg'),
(50,'storage/images/Panasonic_Table_Lamp_3.jpg'),
(1,'storage/images/iphone13_4.jpg'),
(2,'storage/images/iphone-13-pro-max_4.jpg'),
(3,'storage/images/iphone14_4.jpg'),
(4,'storage/images/iphone-14-pro-max_4.jpg'),
(5,'storage/images/iphone15_4.jpg'),
(6,'storage/images/samsung_galaxy_S23_4.jpg'),
(7,'storage/images/samsung_galaxy_A54_4.jpg'),
(8,'storage/images/Samsung_QLED-TV_65_4.jpg'),
(9,'storage/images/Samsung_Frame_ TV_ 50_4.jpg'),
(10,'storage/images/LG_OLED_TV_55_4.jpg'),
(11,'storage/images/LG_Nanocell_TV_65_4.jpg'),
(12,'storage/images/Asus_Zenbook_14_4.jpg'),
(13,'storage/images/Asus_TUF_Gaming_A15_4.jpg'),
(14,'storage/images/Lenovo_Thinkpad_X1_Carbon_4.jpg'),
(15,'storage/images/Lenovo_Yoga_9i_4.jpg'),
(16,'storage/images/Panasonic_NR_4.jpg'),
(17,'storage/images/BA228PKV1_4.jpg'),
(18,'storage/images/RS682WE_4.jpg'),
(19,'storage/images/AG66VA(XK)_4.jpg'),
(20,'storage/images/B1000GV_4.jpg'),
(21,'storage/images/BH85S2V_4.jpg'),
(22,'storage/images/WW90J54E0BWSV_4.jpg'),
(23,'storage/images/WA10J5710SGSV_4.jpg'),
(24,'storage/images/CL563_4.jpg'),
(25,'storage/images/CL305_4.jpg'),
(26,'storage/images/Toshiba_VC_PG514_4.jpg'),
(27,'storage/images/Toshiba_4.jpg'),
(28,'storage/images/13N3KV_4.jpg'),
(29,'storage/images/09BKCV_4.jpg'),
(30,'storage/images/H09VNA_4.jpg'),
(31,'storage/images/H12VNA_4.jpg'),
(32,'storage/images/may-loc-khong-khi-samsung-ax90r7080-1.jpg'),
(33,'storage/images/Samsung_VF_R21_4.jpg'),
(34,'storage/images/LG_air_4.jpg'),
(35,'storage/images/LG_WF_232_4.jpg'),
(36,'storage/images/SK10Y_4.jpg'),
(37,'storage/images/RL4_4.jpg'),
(38,'storage/images/Q950A_4.jpg'),
(39,'storage/images/MX-T70_4.jpg'),
(40,'storage/images/airportpro_4.jpg'),
(41,'storage/images/airportpromax_4.jpg'),
(42,'storage/images/1000XM5_4.jpg'),
(43,'storage/images/H910N_4.jpg'),
(44,'storage/images/Sunhouse_Modern_LED_Wall_Light_4.jpg'),
(45,'storage/images/Sunhouse_classic_wall_light_4.jpg'),
(46,'storage/images/Kangaroo_Elegant_Wall_Light_4.jpg'),
(47,'storage/images/Kangaroo_Led_Wall_Lamp_4.jpg'),
(48,'storage/images/Kangaroo_Table_Lamp_4.jpg'),
(49,'storage/images/xiaomi_lamp_4.jpg'),
(50,'storage/images/Panasonic_Table_Lamp_4.jpg');

INSERT INTO reviews (product_id, user_id, rating, comment)
VALUES
    (1, 1, 4, 'Great phone, good camera quality'),
    (2, 1, 5, 'Very comfortable and durable shoes'),
    (3, 1, 3, 'Informative book, but a bit technical'),
    (4, 1, 5, 'Excellent TV with vibrant colors'),
    (5, 1, 4, 'Nice set, modern design fits well in my home'),
    (6, 1, 2, 'Not as expected, but still okay'),
    (7, 1, 4, 'Good value for the price'),
    (8, 1, 3, 'Average performance, could be better'),
    (9, 1, 5, 'Love it, would definitely recommend'),
    (10, 1, 1, 'Not satisfied with the product'),
    (11, 1, 3, 'It works, but has some issues'),
    (12, 1, 4, 'Really good product for the price'),
    (13, 1, 5, 'Excellent quality, very pleased'),
    (14, 1, 2, 'Disappointed with the purchase'),
    (15, 1, 4, 'Great for everyday use'),
    (16, 1, 3, 'Not bad, but could be improved'),
    (17, 1, 5, 'Amazing quality, very happy'),
    (18, 1, 2, 'Below expectations'),
    (19, 1, 4, 'Very functional and practical'),
    (20, 1, 5, 'Fantastic product, would buy again'),
    (21, 1, 3, 'Decent product, meets the needs'),
    (22, 1, 4, 'Good purchase for the money'),
    (23, 1, 5, 'Top-notch quality'),
    (24, 1, 2, 'Not the best, but okay'),
    (25, 1, 4, 'Satisfactory performance'),
    (26, 1, 3, 'Does the job, but not great'),
    (27, 1, 5, 'Superb product, very satisfied'),
    (28, 1, 2, 'Not worth the money'),
    (29, 1, 4, 'Pretty good overall'),
    (30, 1, 5, 'Exceeded my expectations'),
    (31, 1, 3, 'Okay, but not great'),
    (32, 1, 4, 'Good product, would recommend'),
    (33, 1, 5, 'Fantastic, would buy again'),
    (34, 1, 2, 'Not impressed with the quality'),
    (35, 1, 4, 'Really good, worth the money'),
    (36, 1, 3, 'Average product'),
    (37, 1, 5, 'Excellent quality and performance'),
    (38, 1, 2, 'Disappointing experience'),
    (39, 1, 4, 'Good value for the price'),
    (40, 1, 5, 'Amazing quality, very pleased'),
    (41, 1, 3, 'It’s okay, not the best'),
    (42, 1, 4, 'Pretty good product'),
    (43, 1, 5, 'Highly recommend this product'),
    (44, 1, 2, 'Not very happy with the purchase'),
    (45, 1, 4, 'Good performance for the price'),
    (46, 1, 3, 'Meets expectations'),
    (47, 1, 5, 'Outstanding quality'),
    (48, 1, 2, 'Below my expectations'),
    (49, 1, 4, 'Very good product'),
    (50, 1, 5, 'Excellent, would definitely buy again'),
    (1, 1, 5, 'Excellent product, very satisfied'),
    (2, 1, 3, 'Average quality, acceptable'),
    (3, 1, 4, 'Good value for the price'),
    (4, 1, 2, 'Could be improved'),
    (5, 1, 5, 'Highly recommend this product'),
    (6, 1, 4, 'Very functional and useful'),
    (7, 1, 2, 'Not as expected'),
    (8, 1, 3, 'Decent quality'),
    (9, 1, 5, 'Fantastic, would buy again'),
    (10, 1, 1, 'Very disappointed'),
    (11, 1, 4, 'Good performance overall'),
    (12, 1, 2, 'Not worth the money'),
    (13, 1, 5, 'Exceeded my expectations'),
    (14, 1, 3, 'Satisfactory but not great'),
    (15, 1, 4, 'Good product, worth the price'),
    (16, 1, 1, 'Poor quality'),
    (17, 1, 5, 'Excellent value for the money'),
    (18, 1, 2, 'Below expectations'),
    (19, 1, 4, 'Very good product'),
    (20, 1, 5, 'Superb quality'),
    (21, 1, 3, 'Meets the basic needs'),
    (22, 1, 4, 'Good buy'),
    (23, 1, 5, 'Top-notch product'),
    (24, 1, 2, 'Not very good'),
    (25, 1, 4, 'Reliable product'),
    (26, 1, 3, 'Average, could be better'),
    (27, 1, 5, 'Fantastic quality'),
    (28, 1, 2, 'Disappointed'),
    (29, 1, 4, 'Quite good'),
    (30, 1, 5, 'Excellent, very happy'),
    (31, 1, 3, 'Okay product'),
    (32, 1, 4, 'Good quality'),
    (33, 1, 5, 'Highly recommended'),
    (34, 1, 2, 'Not great'),
    (35, 1, 4, 'Very good quality'),
    (36, 1, 3, 'Average performance'),
    (37, 1, 5, 'Outstanding product'),
    (38, 1, 2, 'Not satisfied'),
    (39, 1, 4, 'Good value'),
    (40, 1, 5, 'Amazing, would buy again'),
    (41, 1, 3, 'It is okay'),
    (42, 1, 4, 'Good value for money'),
    (43, 1, 5, 'Fantastic quality'),
    (44, 1, 2, 'Below expectations'),
    (45, 1, 4, 'Good product overall'),
    (46, 1, 3, 'Meets the expectations'),
    (47, 1, 5, 'Excellent'),
    (48, 1, 2, 'Not very pleased'),
    (49, 1, 4, 'Good product'),
    (50, 1, 5, 'Great quality, very satisfied');
INSERT INTO users (id, name, password, email, phone, address, role, created_at, updated_at) VALUES
(1, 'hieu', '$2y$10$WOLQSBftBiLjfBWfG0Q7aePFFQUwP6cHwTSeboozND8H/qTh4qdIq', 'phihieu6789a@gmail.com', '5553428400', '1600 Amphitheatre Parkway', 'user', '2024-08-06 15:13:00', '2024-08-06 15:13:00'),
(2, 'hieu', '$2y$10$jSax9eQLwYwM.4UGuOVxBu/9rXbqMswQSHaJM1Hpycvpqd68LWrRa', 'admin@com.vn', '5553428400', '1600 Amphitheatre Parkway', 'admin', '2024-08-06 15:18:00', '2024-08-06 15:18:00');
